version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio-upload-microservice
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./db/minio-data:/data

  mongodb:
    image: mongo:7.0.5
    container_name: mongodb-upload-microservice
    ports:
      - "27017:27017"
    environment:
      MONGO_INIT_USERNAME: root
      MONGO_INIT_PASSWORD: password
      MONGO_INIT_DATABASE: donvert-mongodb-upload
    volumes:
      - ./db/mongo-data:/data/db

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      -
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres-db:/var/lib/postgresql
